/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;

/**
 *
 * @author ariad
 */
public class InicialCRUD extends javax.swing.JFrame {

    
    public InicialCRUD() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(245,245,245)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        autoresCrud = new javax.swing.JButton();
        editoraCrud = new javax.swing.JButton();
        categoriasCrud = new javax.swing.JButton();
        livros = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        amigosCrud = new javax.swing.JButton();
        EmprestimoCrud = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setName("jframe"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Vladimir Script", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BookClub");
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 80));
        jLabel1.setMinimumSize(new java.awt.Dimension(200, 80));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 200));

        autoresCrud.setBackground(new java.awt.Color(245, 245, 245));
        autoresCrud.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        autoresCrud.setText("Autores");
        autoresCrud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoresCrudActionPerformed(evt);
            }
        });

        editoraCrud.setBackground(new java.awt.Color(245, 245, 245));
        editoraCrud.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        editoraCrud.setText("Editora");
        editoraCrud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editoraCrudActionPerformed(evt);
            }
        });

        categoriasCrud.setBackground(new java.awt.Color(245, 245, 245));
        categoriasCrud.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        categoriasCrud.setText("Categorias");
        categoriasCrud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriasCrudActionPerformed(evt);
            }
        });

        livros.setBackground(new java.awt.Color(245, 245, 245));
        livros.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        livros.setText("Livros");
        livros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livrosActionPerformed(evt);
            }
        });

        sair.setFont(new java.awt.Font("Arial Narrow", 1, 10)); // NOI18N
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        amigosCrud.setBackground(new java.awt.Color(245, 245, 245));
        amigosCrud.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        amigosCrud.setText("Amigos");
        amigosCrud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amigosCrudActionPerformed(evt);
            }
        });

        EmprestimoCrud.setBackground(new java.awt.Color(245, 245, 245));
        EmprestimoCrud.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        EmprestimoCrud.setText("Emprestimo");
        EmprestimoCrud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmprestimoCrudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(autoresCrud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(categoriasCrud, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(editoraCrud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(livros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(amigosCrud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(EmprestimoCrud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(211, Short.MAX_VALUE)
                .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(livros, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoresCrud, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editoraCrud, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoriasCrud, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amigosCrud, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmprestimoCrud, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void autoresCrudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoresCrudActionPerformed
       new AutoresCRUD().setVisible(true);
       this.dispose(); 
    }//GEN-LAST:event_autoresCrudActionPerformed

    private void editoraCrudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editoraCrudActionPerformed
       new EditoraCRUD().setVisible(true);
       this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_editoraCrudActionPerformed

    private void categoriasCrudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriasCrudActionPerformed
       new CategoriasCRUD().setVisible(true);
       this.dispose();       
    }//GEN-LAST:event_categoriasCrudActionPerformed

    private void livrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livrosActionPerformed
        new LivrosCRUD().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_livrosActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
      dispose();
    }//GEN-LAST:event_sairActionPerformed

    private void amigosCrudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amigosCrudActionPerformed
        new AmigosCRUD().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_amigosCrudActionPerformed

    private void EmprestimoCrudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmprestimoCrudActionPerformed
        new EmprestimosCRUD().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EmprestimoCrudActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicialCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicialCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicialCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicialCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicialCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EmprestimoCrud;
    private javax.swing.JButton amigosCrud;
    private javax.swing.JButton autoresCrud;
    private javax.swing.JButton categoriasCrud;
    private javax.swing.JButton editoraCrud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JButton livros;
    private javax.swing.JButton sair;
    // End of variables declaration//GEN-END:variables
}
